### ISSUE TITLE
ERROR: python_dfn has an invalid path name: ~/.conda/envs/python2/bin/python

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#1]
Hello, 

I got this error and would you please help: 
I don't have admin privileges so I have to create a new environment for python named python2. My python is in ~/.conda/envs/python2/bin/python and I was able to install pydfnworks successfully. 
When I run dfnWorks, I got this error: 
ERROR: python_dfn has an invalid path name: ~/.conda/envs/python2/bin/python
I guess it was something wrong when the code validates the path name. I fixed this error by skipping all the validations of path name in the file path.py but other errors come: 
/home/hpham/.conda/envs/python2/bin/python: can't open file 'compile.py': [Errno 2] No such file or directory
(I checked and found that the compile.py is in folder /home/hpham/.conda/envs/python2/bin/)
Would you please have a look at and let me know the solution? 
Thank you and attached please find the modified path.py

--Hai
[paths.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/851743/paths.txt)

**Comment by deknapp** [comment]
Hai, 
I am looking into this now - will post again when I figure it out.
-Nathan

**Comment by deknapp** [comment]
@pvh1983 : 
how are you running dfnWorks? Can you give me your command line input / what input files or test you are using?

**Comment by deknapp** [comment]
@pvh1983 Try this:
1. Instead of using ~, write your home directory explicitly (/home/hpham) . 
2. Re-install pydfnworks using python setup.py install --user. Then, use your original environment for python. This should be possible without admin privieges.
Let me know if that works. 
-Nathan (on the dfnWorks team)

**Comment by pvh1983** [comment]
Thanks Nathan!

I am running dfnWorks using a Linux cluster and I have no problem at all when running the dfnWorks 1.0 in this cluster. From the tests folder I run this command:
python /projects/DFN/dfnWorks-Version2.0/pydfnworks/bin/run.py -name output -input 4_user_rectangles.txt -ncpus 6
I have changed the file path.py with ~ replaced by /home/hpham and re-install pydfnworks but it did not work. The error is 
/home/hpham/.conda/envs/python2/bin/python: can't open file 'compile.py': [Errno 2] No such file or directory

I can't use the original Python environment as I can't install pydfnworks there. 
 and also, I can not run setup with my account:
$ which python
/apps/miniconda2-python2/bin/python
$python setup.py install --hpham
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --hpham not recognized

Thank you, 
--Hai.

**Comment by deknapp** [comment]
I should have clarified. Use --user, not --hpham. when you run setup.py . 

So python setup.py install --user, not python setup.pz install --hpham

**Comment by deknapp** [comment]
I think the problem is that python setup.py install is not installing the pydfnworks package to your new Python environment, it is installing it to your default Python. That is probably why it cannot find compile.py . Let me know if using the --user option works.

**Comment by deknapp** [comment]
@pvh1983 was this issue resolved? let me know.

**Comment by pvh1983** [comment]
@deknapp thanks for your quick response. I have tried to re-instal dnfWork2.0 from the beginning and still have problems. This comes as I don't have admin right to install python. As as result, I wasn't able to install pydfnworks using original python environment. I am trying to create a new python enviromnent and re-install dfnWorks again. 

hpham@oasis-login-s01: ~ $ pwd
/home/hpham
hpham@oasis-login-s01: ~ $ git clone https://github.com/dfnWorks/dfnWorks-Version2.0.git
hpham@oasis-login-s01: ~ $ cd dfnWorks-Version2.0/pydfnworks
hpham@oasis-login-s01: ~/dfnWorks-Version2.0/pydfnworks $ which python
/apps/miniconda2-python2-WRF/bin/python
hpham@oasis-login-s01: ~/dfnWorks-Version2.0/pydfnworks $ python --version
Python 2.7.13 :: Continuum Analytics, Inc.

[Modify the path.py - see attachment]

hpham@oasis-login-s01: ~/dfnWorks-Version2.0/pydfnworks $ python setup.py install --user
It took several around 10 minutes to compile. There are a lot of warning and red lines.

hpham@oasis-login-s01: ~/dfnWorks-Version2.0/tests $ python /home/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py -name output -input 4_user_rectangles.txt -ncpus 6
Traceback (most recent call last):
  File "/home/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py", line 10, in <module>
    from pydfnworks import *
  File "/home/hpham/.local/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/__init__.py", line 1, in <module>
    from dfnworks import *
  File "/home/hpham/.local/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/dfnworks.py", line 12, in <module>
    class DFNWORKS(Frozen):
  File "/home/hpham/.local/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/dfnworks.py", line 35, in DFNWORKS
    from flow import dfnFlow
  File "/home/hpham/.local/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/flow.py", line 9, in <module>
    import h5py
ImportError: No module named h5py
[paths.py.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/855779/paths.py.txt)

**Comment by deknapp** [comment]
@pvh1983 

Can you check that the module h5py is installed on your machine? You can do this by:

1. open a python shell (type python in your terminal)
2. import sys
3. 'h5py' in sys.modules

If the result of 3 is False, run pip install h5py . In the meantime, I'll try to modify the code to automatically install h5py for you. 

Let me know if you get True or False after running the steps above. 

Thanks,
Nathan

**Comment by pvh1983** [comment]
It is failed, as I cannot install anything to the original python environment.

hpham@oasis-login-s01: ~/dfnWorks-Version2.0/pydfnworks $ pip install h5py
Collecting h5py
  Downloading h5py-2.7.0-cp27-cp27mu-manylinux1_x86_64.whl (4.3MB)
    100% |████████████████████████████████| 4.4MB 142kB/s
Requirement already satisfied: numpy>=1.7 in /apps/miniconda2-python2-WRF/lib/python2.7/site-packages (from h5py)
Requirement already satisfied: six in /apps/miniconda2-python2-WRF/lib/python2.7/site-packages (from h5py)
Installing collected packages: h5py
Exception:
Traceback (most recent call last):
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/apps/miniconda2-python2-WRF/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/apps/miniconda2-python2-WRF/lib/python2.7/site-packages/h5py'

**Comment by deknapp** [comment]
@pvh1983 

I made a change to the repo, can you clone again? python setup.py install --user should now automatically get the h5py module for you. Let me know if that works.

**Comment by pvh1983** [comment]
I downloaded the new version but there was an error when installing h5py. The log file is attached:
[logerr.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/855909/logerr.txt)

**Comment by pvh1983** [comment]
There is another bug, I guess. Whatever I change the path in the path.py, even though I re-run "python setup.py install" (I am working with a new python environment which I have admin right so no --user was used), the paths were not updated. It keeps using the old paths. In my new python environment, pydfnworks was successfully installed:

(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/tests $ which python
~/.conda/envs/hpham_pth2/bin/python
(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/tests $ conda list
cycler                    0.10.0                    <pip>
functools32               3.2.3.post2               <pip>
h5py                      2.6.0               np112py27_2
hdf5                      1.8.17                        1
libgfortran               3.0.0                         1
libxcb                    1.12                          1
matplotlib                2.0.0                     <pip>
mkl                       2017.0.1                      0
numpy                     1.12.1                   py27_0
openssl                   1.0.2k                        1
pip                       9.0.1                    py27_1
pydfnworks                2.0                       <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.0                     <pip>
pytz                      2016.10                   <pip>
readline                  6.2                           2
scipy                     0.19.0              np112py27_0
setuptools                27.2.0                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
subprocess32              3.2.7                     <pip>
system                    5.8                           2
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
zlib                      1.2.8                         3

**Comment by deknapp** [comment]
@pvh1983

I'm glad you got pydfnworks installed in your new environment. 

Can you please tell me the dfn_python environment variable you are using in paths.py? 

Furthermore, are you changing the paths.py in the directory pydfnworks/pydfnworks/, or in the build files. For this to work you have to change it pydfnworks/pydfnworks.

Thanks,
Nathan

**Comment by deknapp** [comment]
@pvh1983 

The 'dfn_python' environment variable set in pydfnworks/pydfnworks/paths.py must match the python executable of your new Python environment - is this the case?

**Comment by pvh1983** [comment]
Yes. Two paths are the same. I changed the path in pydfnworks/pydfnworks/paths.py. I don't even know where are the build files.

The python path defined in pydfnworks/pydfnworks/paths.py is
    os.environ['python_dfn'] = '/home/hpham/.conda/envs/hpham_pth2/bin/python'

I would like to change this path:
 os.environ['DFNWORKS_PATH'] = 'home/hpham/dfnWorks-Version2.0/'
to this path: 
 os.environ['DFNWORKS_PATH'] = '/dfnnew/home/hpham/dfnWorks-Version2.0/'
I re-run "python setup.py install", but it did not change when I run dfnWorks:

(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/pydfnworks 
$ cd ../tests/
(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/tests $ python /home/hpham/dfnnew/dfnWorks-Version2.0/pydfnworks/bin/run.py -name output -input 4_user_rectangles.txt -ncpus 6
ERROR: DFNWORKS_PATH has an invalid path name: /home/hpham/dfnWorks-Version2.0/

**Comment by deknapp** [comment]
@pvh1983 

I think I understand the problem now. 

When you just run python setup.py install, it does not use your new Python environment, it uses the system default python environment. Try running:

/home/hpham/.conda/envs/hpham_pth2/bin/python setup.py install

instead. Let me know if this works.

**Comment by pvh1983** [comment]
Thanks Nathan but it showed the same error. Where are the build files? How can I remove all build files and re-setup pydfnwork? Thank you!

(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/pydfnworks 
$ /home/hpham/.conda/envs/hpham_pth2/bin/python setup.py install
(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/pydfnworks $ cd ../tests/
(hpham_pth2) hpham@oasis-login-s01: ~/dfnnew/dfnWorks-Version2.0/tests $ python /home/hpham/dfnnew/dfnWorks-Version2.0/pydfnworks/bin/run.py -name output -input 4_user_rectangles.txt -ncpus 6
ERROR: DFNWORKS_PATH has an invalid path name: /home/hpham/dfnWorks-Version2.0/

**Comment by pvh1983** [comment]
I saw after the intallation process, the code copies the file compile.py to /home/hpham/.conda/envs/hpham_pth2/bin/ but when I run the model, this error shows. Do you know why? 
(hpham_pth2) hpham@oasis-login-s01: /scratch/hpham/dfnWorks-Version2.0/tests $ python /scratch/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py -name output -input 4_user_rectangles.txt -ncpus 6
Compiling executables
/home/hpham/.conda/envs/hpham_pth2/bin/python: can't open file 'compile.py': [Errno 2] No such file or directory

**Comment by pvh1983** [comment]
Hi Nathan, 

I changed to this directory and the above problem related to compile.py is solve: /dfnWorks-Version2.0/pydfnworks/bin
(hpham_pth2) hpham@oasis-login-s01: /scratch/hpham/dfnWorks-Version2.0/pydfnworks/bin $ python run.py -name output -input /scratch/hpham/dfnWorks-Version2.0/tests/4_user_rectangles.txt -ncpus 6

but another error comes
run.py: error: unrecognized arguments: -ncpus 6

Would you please suggest how to overcome this error? 

Thank you, 
Hai.

**Comment by pvh1983** [comment]
oh, forget about this, -ncpus 6 should be -ncpu 6 (without s)

**Comment by pvh1983** [comment]
FYI A typo in the manual: 
In the PDF manual: 
python dfnWorks-Version2.0/pydfnworks/bin/run.py -name 4_user_defined_rectangles -input dfnworks_main/tests/**4_user_rectangles.txt** -ncpus 4

but in the tests folder, the file name is **4_user_defined_rectangles.txt**

**I got dfnWorks run finally!!! but there is another error. Would you please let me know what was wrong?** 

python /scratch/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py -name 4_user_defined_rectangles -input /scratch/hpham/dfnWorks-Version2.0/tests/4_user_defined_rectangles.txt -ncpu 6

-->Creating DFN class: Complete
Jobname:  4_user_defined_rectangles
Number of cpus requested:  6
--> dfnGen input file:  /scratch/hpham/dfnWorks-Version2.0/tests/gen_4_user_rectangles.dat
--> dfnFlow input file:  /scratch/hpham/dfnWorks-Version2.0/tests/dfn_explicit.in
--> dfnTrans input file:  /scratch/hpham/dfnWorks-Version2.0/tests/PTDFN_control.dat
================================================================================


Current directory is now: /scratch/hpham/test/4_user_defined_rectangles

Jobname is  4_user_defined_rectangles

ERROR --- Check that the path of your output file is valid.

----Program terminated while parsing input----

**Comment by deknapp** [comment]
@pvh1983 

Can you go to line 640 of pydfnworks/pydfnworks/gen_input.py . Insert a new line at line 641 within the try block that says print ioPaths["output"] . Then check that the directory of ioPaths["output"] exists. 

If it does exist, then check the permissions in the directory. Do you have write access in the directory of the ioPaths["output"] file?

**Comment by pvh1983** [comment]
@deknapp here is the output after I insert line 641. This is the path of a file, not a folder!!! Am I doing correct (gen_input.py file attached)? Also, there is an dupplication: test4frac/test4frac_/. What should I check next? Thank you very much!
Hai. 

Creating test4frac
Current directory is now: /scratch/hpham/ex1/test4frac
Jobname is  test4frac
/scratch/hpham/ex1/test4frac/test4frac/gen_4_user_rectangles_clean.dat
ERROR --- Check that the path of your output file is valid.
----Program terminated while parsing input----
[gen_input.py.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/856237/gen_input.py.txt)

**Comment by deknapp** [comment]
@pvh1983  I'm sorry, it is hard to describe code things by text .

I was not saying it was a folder name, I was asking for the name of the folder that contains the file. 

Give me some time to try to fix this, and I will post again and tag you when I have a solution.

**Comment by deknapp** [comment]
@pvh1983 can you try again now? In my last commit I tried to fix this bug. 

I appreciate you posting this issue, it is good to find these bugs as early as possible.

**Comment by pvh1983** [comment]
Thanks @deknapp. It seems that there is something wrong with path file: There isn't a "/" in between this: 
/hphamdfnWorks-Version2.0/

Current directory is now: /scratch/hpham/ex1/test4frac
Jobname is  test4frac
ERROR: dfnGen input file path:  /home/hphamdfnWorks-Version2.0/tests/gen_4_user_rectangles.dat  does not exist
Unable to copy dfnGen input file
/home/hphamdfnWorks-Version2.0/tests/gen_4_user_rectangles.dat
Exiting

**Comment by pvh1983** [comment]
Thanks @deknapp but I see the same error.

Current directory is now: /scratch/hpham/ex1/test4frac
Jobname is  test4frac
/scratch/hpham/ex1/test4frac/test4frac/gen_4_user_rectangles_clean.dat
hpham marked line 642
ERROR --- Check that the path of your output file is valid.
----Program terminated while parsing input----

**Comment by deknapp** [comment]
Can you confirm two things @pvh1983:

1. are you sure you cloned the last commit?

2. did you rerun:

/home/hpham/.conda/envs/hpham_pth2/bin/python setup.py install

3. when you ran the test, did you use:

/home/hpham/.conda/envs/hpham_pth2/bin/python /pydfnworks/bin/run.py -name 4_user_defined_rectangles -input dfnworks_main/tests/4_user_rectangles.txt -ncpus 4

From your second to last post I am confused as to whether you are using your new python environment or your system default. Please make sure with ANY command you run using Python that you are using/home/hpham/.conda/envs/hpham_pth2/bin/python . Because you have installed pydfnworks to this new environment, using the system default python may not work, and I have to eliminate this possibility when trying to fix the bugs you are getting.

**Comment by pvh1983** [comment]
Dear @deknapp, 

(1) I cloned three times already so I am sure I used the latest version. I also do " pip uninstall pydfnworks" to remove the old one before I run "/home/hpham/.conda/envs/hpham_pth2/bin/python setup.py install"
(2) and (3)  Yes, I used these commands.

I activate the new Python environment named hpham_pth2 so I am sure that I use correct Python. If not, there will be an error that pydfnwork could not be imported.

Also, do I have to stay at a specific folder when I run for the test example? I have tried several locations and the error stills the same.

Please have a look at the bug and I do hope you can fix it soon.
Thank you, 
Hai. 

Last several lines of OUTPUT:
Creating 4_user_defined_rectangles
Current directory is now: /home/hpham/dfnWorks-Version2.0/pydfnworks/bin/4_user_defined_rectangles
Jobname is  4_user_defined_rectangles
/home/hpham/dfnWorks-Version2.0/pydfnworks/bin/4_user_defined_rectangles/4_user_defined_rectangles/gen_4_user_rectangles_clean.dat
ERROR --- Check that the path of your output file is valid.
----Program terminated while parsing input----

You may revise the PDF manual:
(1) to compile the program for the first time, I have to go to /pydfnworks/bin directory (otherwise, there will be an error of not found compile.py). 
(2) -ncpus 4 should be -ncpu 4
(3) 4_user_rectangles.txt should be 4_user_defined_rectangles.txt

**Comment by hymanjd** [comment]
@pvh1983 try using an absolute path for -name

**Comment by pvh1983** [comment]
Great ! @deknapp that error is bypassed but another error comes. Where should I look at to fix this error? Thanks!!!

(hpham_pth2) hpham@oasis-login-s01: /scratch/hpham $ /home/hpham/.conda/envs/hpham_pth2/bin/python /home/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py -name /scratch/hpham/4_user_defined_rectangles -input /home/hpham/dfnWorks-Version2.0/tests/4_user_defined_rectangles.txt -ncpu 4

==================================================================

Current directory is now: /scratch/hpham/4_user_defined_rectangles
Jobname is  /scratch/hpham/4_user_defined_rectangles
/scratch/hpham/4_user_defined_rectangles/gen_4_user_rectangles_clean.dat
--> Checking input data
--> Input Data:  /home/hpham/dfnWorks-Version2.0/tests/gen_4_user_rectangles.dat
--> Output File:  /scratch/hpham/4_user_defined_rectangles/gen_4_user_rectangles_clean.dat
WARNING --- You have set the number of ellipse families to 0, outside user-defined ellipses, no ellipses will be generated.
WARNING --- You have set the number of rectangle families to 0, outside user-defined rectangles, no rectangles will be generated.

ERROR --- "UserRect_Input_File_Path" is not a valid path.

----Program terminated while parsing input----

**Comment by deknapp** [comment]
@pvh1983 You have to run fix_paths.py, which is described in the documentation. This corrects the path names in the test files.

**Comment by deknapp** [comment]
@pvh1983 Can you spend a few days trying to get dfnWorks to run on your own, and if you still have bugs, post them here? A lot of these bugs are path name issues that you can resolve.

Thanks, Nathan

**Comment by deknapp** [comment]
@pvh1983  
In the meantime, I am running other tests which should hopefully eliminate some of the remaining bugs.

**Comment by pvh1983** [comment]
Thanks @deknapp for your great help! I think all bugs related to paths are solved. Now I got another error related to output_report. Is this because of I am missing a python library? Thank you!!!

conda list
cycler                    0.10.0                    <pip>
functools32               3.2.3.post2               <pip>
h5py                      2.6.0               np112py27_2
hdf5                      1.8.17                        1
libgfortran               3.0.0                         1
libxcb                    1.12                          1
matplotlib                2.0.0                     <pip>
mkl                       2017.0.1                      0
numpy                     1.12.1                   py27_0
openssl                   1.0.2k                        1
pip                       9.0.1                    py27_1
pydfnworks                2.0                       <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.0                     <pip>
pytz                      2016.10                   <pip>
readline                  6.2                           2
scipy                     0.19.0              np112py27_0
setuptools                27.2.0                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
subprocess32              3.2.7                     <pip>
system                    5.8                           2
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
zlib                      1.2.8                         3


...
Generation Succeeded
--------------------------------------------------------------------------------
--> Creating Report of DFN generation
Writing output into:  4_user_defined_rectangles_output_report.pdf
Traceback (most recent call last):
  File "/home/hpham/dfnWorks-Version2.0/pydfnworks/bin/run.py", line 24, in <module>
    DFN.dfnGen()
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/generator.py", line 36, in dfnGen
    self.output_report()
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/gen_output.py", line 528, in output_report
    graphTranslations()
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/gen_output.py", line 139, in graphTranslations
    transHist('X', xAll, xUnremoved)
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/pydfnworks-2.0-py2.7.egg/pydfnworks/gen_output.py", line 100, in transHist
    plt.subplots()
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/home/hpham/.conda/envs/hpham_pth2/lib/python2.7/lib-tk/Tkinter.py", line 1820, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by deknapp** [comment]
It's a problem with your setup, not dfnWorks. Can't help you here.

" no display name and no $DISPLAY environment variable " 

Only advice I can offer is make sure you have logged into your server with ssh -X [SERVER_NAME]

**Comment by hymanjd** [comment]
@pvh1983 , output_report is trying to create images for a pdf concerning generation. @deknapp suggestion to ssh -X should work if you have the machine set up correctly. 

If you can't get that to work, You can skip the output_report by running run_explicit.py rather than run.py and commenting out the line

DFN.output_report()

You will also need to uncomment all the following lines starting from 

DFN.lagrit2pflotran()

**Comment by pvh1983** [comment]
@deknapp @hymanjd that ssh -X helped. I was able to re-produce the example with 4 fractures. I can't wait to test dfnWorks 2.0 for a real case study tomorrow. 
Thank you for your great supports!!!
-Hai.
