### ISSUE TITLE
Incorrect P32 calculation

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#11]
Hello, 

I think there is an error when DFNGen calculates fracture surface area and P32. It seems that the code doubles the value of fracture surface area.  Attached please find input files and the output log. 
I think the total surface area should be 4 m^2 in this example but the output printed 8 m^2. 
I really appreciate if you could have a look at. 

Thank you, 
-Hai. 

[define_4_user_rects.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/1178699/define_4_user_rects.txt)
[gen_4_user_rectangles.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/1178698/gen_4_user_rectangles.txt)
[DFN_output.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/1178704/DFN_output.txt)
[radii_Final.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/1178703/radii_Final.txt)
![4fracs](https://user-images.githubusercontent.com/9260965/28653268-8381a4e6-7241-11e7-8ec1-9f4632a11551.png)

**Comment by hymanjd** [comment]
Surface area is computed using both sides of the plane. The value of 8 m^2 is correct.
