### ISSUE TITLE
Refine mesh at a certain area?

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#12]
Hello, 

I would like to have a very fine mesh at a certain (x,y) location (e.g, at a pumping/injection well location). Do you have any thoughts/suggestions on how to implement it using dfnWorks? I can add an user-defined vertically fracture for this but this creates too many artificial connections which is not good.  

Thank you, 
Hai.

**Comment by hymanjd** [comment]
Can you limit the the vertical extend of the user-defined fracture? That might remove some of the artificial connections but still refine the mesh locally.

Another option would be using LaGriT to refine in that region and tag elements based on spatial coordinates after full_mesh.inp has been made. This technique isn't standard within dfnWorks and will require new script development.

**Comment by pvh1983** [comment]
Thanks @hymanjd . I am really interested in the second option. Would you please provide me an example of LaGriT code for  well tagging and a general picture of how to include it in the dfnWorks?  I am looking for a mesh around the injection/pumping well which is similar to this: 

![image](https://user-images.githubusercontent.com/9260965/32234562-66f0c1e8-be1a-11e7-8bfb-0973fed07c03.png)

Thank you!
Hai.

**Comment by hymanjd** [comment]
I suggest you contact the LaGriT team at LANL to construct a workflow as it's not directly an issue with dfnWorks.
