### ISSUE TITLE
MESH CHECKING HAS FAILED

### ISSUE THREAD

**Issue by Chuanyao-Zhong** [dfnWorks/dfnWorks-Version2.0#16]
Dear SIr/Madam,

I failed in running the 1st example case: "4_user_defined_rects", it seems that I am stuck at the process of "Meshing Network Using LaGriT: Starting", the issue I encountered with is shown below.

![issue Chuanyao](https://user-images.githubusercontent.com/56650438/72548703-746a1280-384c-11ea-9010-e108d2274154.png)

I wonder if it is because the path I set for LaGriT.exe in paths.py (under the file pydfnworks/pydfnworks/general) is incorrect? My setting of paths are shown below.

![issue Chuanyao2](https://user-images.githubusercontent.com/56650438/72548978-0d009280-384d-11ea-8835-0a33341cb8bc.png)

Could you please give me some advice? Thank you so much!

Kindest regards,
Chuanyao
University of Alberta

**Comment by hymanjd** [comment]
Hi Chuanyao,

You need to have the EXE paths set to the actually executable not the directories, which is what you have now. Here's an example of what it should like:

   if os.path.isfile(DFNPARAMS):
        with open(DFNPARAMS, 'r') as f:
            env_paths = json.load(f)
    # Or, change the paths here
    else:
        env_paths = {
            'dfnworks_PATH': '/Users/jhyman/src/dfnworks-main/',
            'PETSC_DIR': '/Users/jhyman/src/petsc/',
            'PETSC_ARCH': '/arch-darwin-c-debug/',
            'PFLOTRAN_EXE': '/Users/jhyman/src/pflotran/src/pflotran/pflotran',
            'PYTHON_EXE': '/anaconda3/bin/python',
            'LAGRIT_EXE': '/Users/jhyman/bin/lagrit',
            'FEHM_EXE': '/Users/jhyman/bin/xfehm'
        }
Give that a try and let me know if that helps. 

Alternatively, you can download the docker container and it has all the paths set for you. If you do not need to modify the source code, we strongly recommend using the Docker container. You can download that here:

[https://hub.docker.com/r/ees16/dfnworks](url)

Jeffrey

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you for your kind advice!
Currently I do not have Mac or Linux system on my computer, that's why I
have been using the WestGrid computing facilities in Canada (with Linux
system) to try to implelment the dfnWorks, it seems that the Docker
container could not be installed on WestGrid. So, I think I would have to
continue working on fixing the EXE paths.
Could you please tell me how can I find or creat those actually executable
files? I wonder if there are any specific filenames and filename exitension
for those executable files? I have downloaded the packages of LaGriT,
Pflotran, Petsc and FEHM from the GitHub, but I could not find any file
with the ".exe" extension.

Thank you! Looking forward to your reply!
Best regards,
Chuanyao

**Comment by hymanjd** [comment]
You'll need to follow the build instructions in each of those repos. For example, you can follow the instructions in the PFLOTRAN site

https://www.pflotran.org/documentation/user_guide/how_to/installation/linux.html#linux-install

There should be build instructions in the README.md files in FEHM and LaGriT repos.

Good luck!

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you for your kind advice. In order to use the Docker container, I
have installed the Ubuntu 18.04 LTS to run Linux subsystem on my Windows 10
system. The Docker container was installed and the dfnworks v2.2 was
successfully pulled. However, when I was trying to run the dfnWorks
container by typing "docker run -ti ees16/dfnworks:v2.2" as instructed, I
obtained this error (as shown below) and I have no idea why it happened and
how to solve it.

[image: image.png]

docker: Error response from daemon: OCI runtime create failed:
> container_linux.go:346: starting container process caused
> "process_linux.go:319: getting the final child's pid from pipe caused
> \"EOF\"": unknown.
> ERRO[0003] error waiting for container: context canceled


I wonder if you have any idea about how to solve this problem? Is it
because dfnWorks does not run on WIndows machine running Ubuntu?

Many thanks,
Chuanyao

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you for your kind advice! In order to use the Docker container, I have installed the Ubuntu 18.04 LTS to run Linux subsystem on my Windows 10 system. The Docker container was installed and the dfnworks v2.2 was successfully pulled. However, when I was trying to run the dfnWorks container by typing "docker run -ti ees16/dfnworks:v2.2" as instructed, I obtained this error (as shown below) and I have no idea why it happened and how to solve it.

![Error Run dfnWorks](https://user-images.githubusercontent.com/56650438/72702294-71527900-3b0f-11ea-96d5-41cf89a3169d.PNG)

"chuanyao@LAPTOP-5ROET1FD:~$ sudo docker run -ti ees16/dfnworks:v2.2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.
ERRO[0003] error waiting for container: context canceled"

I wonder if you have any idea about how to solve this problem? Is it because dfnWorks does not run on Windows machine running Ubuntu?

Many thanks,
Chuanyao

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you for your kind advice. 
I have created a virtual machine with Linux system on my computer. The Docker container was installed and the dfnWorks:v2.2 was pulled. However, I am confused about the steps after the command "docker run -ti ees16/dfnworks:v2.2", do I need to follow the steps from the beginning, like "Setting up dfnWorks" - "Fix paths in test directory" and so on? 
Thanks a lot, looking forward to your reply!

Best regards,
Chuanyao

**Comment by Chuanyao-Zhong** [comment]
![Capture](https://user-images.githubusercontent.com/56650438/72759700-aa343180-3b93-11ea-8565-3e184105ca70.PNG)

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you for your kind advice. 
I have installed a virtual Linux system on my computer and I ran the dfnWorks from the Docker container, and it works!  However, I have no idea how and where to find my results files. It seems that the results are not in the local system. I wonder how can I open the file location and download those results files? Thank you so much! 

![Capture2](https://user-images.githubusercontent.com/56650438/72760721-f92f9600-3b96-11ea-9b30-19c1a73afed4.PNG)

 Kindest regards,
Chuanyao

**Comment by Chuanyao-Zhong** [comment]
I followed the insturctions and tired to use the command "-v LOCAL_FOLDER:/dfnWorks/work" to mount a volume, but it doesn't work (as shown in the figure below)
![Capture4](https://user-images.githubusercontent.com/56650438/72762547-3bf46c80-3b9d-11ea-9201-4472e858df11.PNG)

**Comment by hymanjd** [comment]
@daniellivingston Any ideas?

**Comment by daniellivingston** [comment]
Hi @Chuanyao-Zhong, looking at your screenshot more closely, it's not clear what is going on. Sorry if I'm missing something. It looks like you're trying to mount the volume within the Docker container?

The dfnWorks docker container should be started with a command that looks similar to:

```
docker run -it -v /home/chuanyao/Desktop/Results:/dfnWorks/work/ ees16/dfnworks
```

The examples are configured to output into the `/dfnWorks/work` directory, so trying to mount a different directory will cause crashes or undefined behavior when running the examples.

If you run the command above, and then do:

```
$ cd /dfnWorks/examples/4_user_rects/
$ bash notes.txt
```

then you will see the output in `/dfnWorks/work/4_user_rects_example`, or, on your Ubuntu filesystem, in: `/home/chuanyao/Desktop/Results`.

**Comment by Chuanyao-Zhong** [comment]
Hello Daniel and Jeffrey,

Thank you so much for your kind advice! It works! However, there is one problem that when I was trying to check the liquid pressure by loading the file 'parsed_vtk/dfn_explicit-001.vtk' into Paraview, it gave me a constant liquid pressure everywhere (as shown below), and when I was trying to visualise the trajectories by loading the file 'part_*.inp' in the folder /traj/trajectories/, it gave me only a single path line (as shown below).

Liquid pressure:
![02231](https://user-images.githubusercontent.com/56650438/73007106-1f3c7c80-3dc9-11ea-8d37-916a1cd0363d.PNG)

Trajectories:
![02232](https://user-images.githubusercontent.com/56650438/73007244-75112480-3dc9-11ea-8124-2ad6efbfb6c8.PNG)

I wonder if it is because the case has not been completely run? But I did follow your instructions completely. 
Here is the last few lines that were displayed when the program finished running:
![02233](https://user-images.githubusercontent.com/56650438/73007982-cb329780-3dca-11ea-9957-1e0da828cd99.PNG)

Could you please give me some advice? Thank you so much!

Kindest regards,
Chuanyao

**Comment by hymanjd** [comment]
The pressure you are plotting looks like the initial condition, which is in dfn_explicit-000.vtk. You need to load just dfn_explicit-001.vtk, not dfn_explicit-*.vtk. 

For the trajectories, Paraview thinks that part_*.inp is a time series, so it only plots one particle at a time. You need to load in each trajectory one at a time. 

J

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thanks, it now works well! Sorry to bother you again, I still have a small problem plotting the particle trajectories for the example cases '4_user_defined_ell_uniform', 'exp', 'TPL' and 'Graph based pruning', because I could not find 'part_*.inp' files or any Paraview-supportable files in their '/traj/' folders. Could you please give me some advice on how to plot the trajectories for those sample cases? Thank you so much! 

Kindest regards,
Chuanyao

**Comment by hymanjd** [comment]
Those examples do not produce the part_*.inp by default. You'll need to change out_avs in PTDFN_control.dat from no to yes.

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffery,

Thank you for your kind advice! Sorry to bother you again, I wonder if it is possible to edit those files or the source codes through the Docker container?

Many thanks,
Chuanyao

**Comment by hymanjd** [comment]
Not in the docker container. You need to install via github for that. 

Jeffrey

**Comment by Chuanyao-Zhong** [comment]
Dear Jeffrey,

Thank you so much for your patience and guidance! The problems have been solved.

Kindest regards,
Chuanyao
