### ISSUE TITLE
Fracture Family Locations

### ISSUE THREAD

**Issue by Chuanyao-Zhong** [dfnWorks/dfnWorks-Version2.0#17]
Dear Sir/Madam,

If we are generating multiple fracture families within a grid, could we assign different locations (regions, coordinates) to different fracture families? I noticed that, in the code, we can define which layer the family belongs to, could we also define which region in the domain the family belongs to?

Thanks! Looking forward to your reply!

Best regards,
Chuanyao

**Comment by hymanjd** [comment]
Only assigning families by vertical layers is supported.

**Comment by Chuanyao-Zhong** [comment]
Okay! Thank you!
