### ISSUE TITLE
More than one initial condition defined

### ISSUE THREAD

**Issue by Chuanyao-Zhong** [dfnWorks/dfnWorks-Version2.0#18]
Dear Sir/Madam,

When I was playing with the example case: 4_user_rects, I wanted to change the 'PARTICLES INITIAL POSITIONS' in the PTDFN_control.dat file, so I changed the "init_nf" from 'yes' to "no", then I set the "init_random" (all particles are placed randomly over all fracture surface, not only on boundary edges) to be "yes".  
However, it gave me this error: 

--> Checking Initial Conditions
ERROR!!! More than one initial condition defined
Exiting
Selected Initial Conditions:
:
init_random:
init_random:

I have checked that I turned off all the other intial conditions in the PARTICLES INITIAL POSITIONS section, and I didn't make any changes in other places. 
So I am wondering why it said "More than one initial condition defined", and how could I solve this problem?

Thank you!

Kindest regards,
Chuanyao

![Capture1](https://user-images.githubusercontent.com/56650438/76381503-44566180-631b-11ea-9750-7cbeeba26d32.JPG)
![Capture2](https://user-images.githubusercontent.com/56650438/76381558-66e87a80-631b-11ea-8d3c-2e70ecfd999d.JPG)

**Comment by hymanjd** [comment]
Dear Chuanyao, 

Please post this issue on https://github.com/lanl/dfnWorks/issues and close the issue here. No one is monitoring this page.

Jeffrey

**Comment by Chuanyao-Zhong** [comment]
Ok! Thanks!

Kindest regards,
Chuanyao
