### ISSUE TITLE
string 'family' in parameters*mlgi LaGriT control file should be capital letters 'FAMILY'

### ISSUE THREAD

**Issue by cwgable** [dfnWorks/dfnWorks-Version2.0#3]
string 'family' in parameters*mlgi LaGriT control file should be capital letters 'FAMILY'

The convention is that parameters in a 'define' command should be written in capital letters. 

For example:
parameters_CPU25.mlgi:define / family / 6.0
mesh_poly_CPU25.lgi:cmo / setatt / mo_final / family_id / 1 0 0 / family

The scripts that write the control files should result in the commands being formed as:
parameters_CPU25.mlgi:define / FAMILY / 6.0
mesh_poly_CPU25.lgi:cmo / setatt / mo_final / family_id / 1 0 0 / FAMILY

**Comment by deknapp** [comment]
@cwgable 
Noted - will be updated in next release.

**Comment by cwgable** [comment]
Moved to internal site.
