### ISSUE TITLE
Paraview can sometimes not read *.inp in traj/trajectories

### ISSUE THREAD

**Issue by deknapp** [dfnWorks/dfnWorks-Version2.0#6]
"Thanks Nathan for fixing the error of "MESH CHECKING HAS FAILED" and clean the outputs. The model runs a lot better than before. After a lot of simulations, I found that the code works well for a system of around 2,000 fractures given a model domain of 100x200x100m and P32 around 0.4 (m2/m3). However, when increasing P32 or the number of fractures, I found three more issues:

(3) Sometimes, Paraview could not read *.inp in traj/trajectories. I have tried several versions of Paraview and still seeing the error. It is noted that Paraview could read the *.inp in traj/trajectories outputs from the test cases. I attached an example of and inp file that I couldn't open here as well.
part_784.inp.txt "

**Comment by deknapp** [comment]
The file is here: 
[part_784.inp.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/930227/part_784.inp.txt)

**Comment by deknapp** [comment]
@pvh1983

**Comment by hymanjd** [comment]
@pvh1983 It appears that the avs output is not printing out the correct number of values in the node based attribute header. We will fix and let you know when it is posted.

**Comment by deknapp** [comment]
@hymanjd @pvh1983 
Fixed in commit acbf9144de095c0326de6b505c7de377e4750105
