### ISSUE TITLE
Particle information at a monitoring well

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#8]
Hello, 

I just wonder if there is an available option to obtain particle information when it passes through  a monitoring well inside the model domain? I saw there is the Cylinder Output in PTDFN_control.dat but no option is defined for it. 

Thank you
-Hai

**Comment by hymanjd** [comment]
@pvh1983 No there is not. This could be done by processing individual trajectories. The cylinder output is for dumping particle information at cylindrical control planes.
