### ISSUE TITLE
Allocation memory problem - tempdata Segmentation fault

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#9]
Hello, 
I have seen a lot of these problems when conducting particle tracking. Do you have any suggestions to overcome these errors? 
Thank you!
-Hai

**Comment by hymanjd** [comment]
@pvh1983 There are a number of things that can cause this seg fault. Can you post your input file?

**Comment by pvh1983** [comment]
Just found that it is not your code's error. It was my mistake when modifying the code. Thanks!
